language: go

go:
  - stable

services:
  - docker

env:
  - GO111MODULE=on
  - MYSQL_DS_DSN='mysql://outboxer:qwerty123@tcp(localhost)/test'
  - DS_DSN='postgres://outboxer:qwerty123@localhost/test?sslmode=disable'
  - ES_DSN='amqp://localhost/'

before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/mysql stop

install: true

before_script:
  - docker-compose -f build/docker-compose.yml up -d

script:
  - go test -v -cover -covermode=atomic -coverprofile=tests.out ./...

after_script:
  - docker-compose -f build/docker-compose.yml down -v

after_success:
  - go get github.com/mattn/goveralls
  - $GOPATH/bin/goveralls -coverprofile=tests.out -service travis-ci -repotoken $COVERALLS_TOKEN
