name: Linter
on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

permissions:
  contents: read
  pull-requests: read

jobs:
  lint:
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Lint Code Base
        uses: github/super-linter@v4
        if: github.event_name == 'pull_request'
        env:
          DEFAULT_BRANCH: master
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MD: true
          # VALIDATE_GO: true # This is not currently reliable
          VALIDATE_GITHUB_ACTIONS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  golangci:
    name: Lint Go files
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: v1.29
          args: -c .github/linters/.golangci.yml
