name: Main
on:
  pull_request: { branches: ["*"] }
  push: { branches: [main, master] }

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Install awslocal
      run: |
        pip install awscli-local

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}

    - name: Test
      run: make test
      
    - uses: codecov/codecov-action@v2
      with:
        files: ./tests.out
        fail_ci_if_error: true
        verbose: true
