name: Main
on: [push, pull_request]
jobs:
  test:
    # Job name is Greeting
    name: Test

    runs-on: ubuntu-latest
    container:
      image:  go:1.13-alpine

    steps:
    - name: Install packages
      run: apk add --update make git

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Build the stack
      run: docker-compose -f build/docker-compose.yml up -d

    - name: Test
      run: make test

    - name: Down the stack
      run: docker-compose -f build/docker-compose.yml down -v

    - name: Upload coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        go get github.com/mattn/goveralls
        $GOPATH/bin/goveralls -coverprofile=tests.out -service travis-ci -repotoken $COVERALLS_TOKEN
