name: Main
on:
  pull_request: { branches: ["*"] }
  push: { branches: [main, master] }

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      DEFAULT_REGION: eu-central-1
      AWS_ACCOUNT_ID: "000000000000"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test

    steps:
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x

    - name: Install awslocal
      run: |
        pip install awscli-local

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}

    - name: Build the stack
      run: docker-compose -f build/docker-compose.yml up -d

    - name: Build localstack
      run: | 
        sleep 10
        awslocal kinesis create-stream --stream-name test --shard-count 1
        make test

    - name: Test
      run: make test-integration

    - name: Down the stack
      if: always()
      run: docker-compose -f build/docker-compose.yml down -v

    - uses: codecov/codecov-action@v3
      with:
        files: ./tests.out
        fail_ci_if_error: false
        verbose: true
